blank_issues_enabled: false
contact_links:
  - name: Installation Help
    url: https://github.com/Thinkersbluff/DGUS-Reloaded_for_CR6-Klipper_Component/blob/DGUS-ReloadedForCR6/Installation_Files/README.md
    about: Installation instructions and troubleshooting
  - name: Development Guide
    url: https://github.com/Thinkersbluff/DGUS-Reloaded_for_CR6-Klipper_Component/blob/DGUS-ReloadedForCR6/Development_Project_Files/Development_Docs/README.md
    about: Contributing and development information