[notifier State_Change]
url: pover://{secrets.pushover_creds.user_key}@{secrets.pushover_creds.token}
events: paused, error, complete
body: "The CR6-SE printer status has changed to {event_name}"
body_format: text
title:

[notifier Macro_Alert]
url: pover://{secrets.pushover_creds.user_key}@{secrets.pushover_creds.token}
events: gcode
body: {event_message}
body_format: text